apiVersion: v1
kind: ConfigMap
metadata:
  name: microservices-config
  namespace: olianiuk-namespace
data:
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_PORT: "5672"
  RABBITMQ_QUEUE: "main_queue"
  USER_SERVICE_URL: "http://user-service:8000"
  PAYMENT_SERVICE_URL: "http://payment-service:8000"