apiVersion: v1
kind: Secret
metadata:
  name: microservices-secret
  namespace: olianiuk-namespace
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:postgres@postgres-service:5432/lab_db"
  SECRET_KEY: "super_secret_jwt_key_for_lab3"